### ISSUE TITLE
Don't copy sup

### ISSUE THREAD

**Issue by signalwerk** [signalwerk/signalwerk.styles#3]
https://codepen.io/lonekorean/pen/WNQjJMV
```css
sup {
  user-select: none;
  color: #31808c;
}
```
